### ISSUE TITLE
Support risk creation for multiple hosts

### ISSUE THREAD

**Issue by dogancanbakir** [projectdiscovery/openrisk#7]
Right now, it only works per host. It would be nice to get risk scores for multiple hosts. For example:
```
domainA.com - 8/10
domainB.com - 3/10
...
```

**Comment by Mzack9999** [comment]
@dogancanbakir I think this would couple very well with https://github.com/projectdiscovery/openrisk/issues/32 for example implementing a method like

```go
func (o *OpenRisk) GetScore(files ...string, ...) ... {...}
```

What do you think?

**Comment by dogancanbakir** [comment]
@Mzack9999 Sure, after defining the API, this task will become a part of the overall function definition. So, let's start by refactoring task #32 and then move on to adding this one.

**Comment by dogancanbakir** [comment]
Just a reminder, this will still work as a single target at a time. But, this time, it'll take multiple nuclei scan files/dir that contain the scan result for just one host, not aggregated output. Let me know, or ping me if you have any questions!
